// Generated by https://quicktype.io

export interface PoseReponseModel {
  message: string;
  poses:   Pose[];
}

export class Pose {
  constructor(
    public action: string,
    public _id:         string,
    public video_title: string,
    public score:       number,
    public keypoints:   Keypoint[]
  ) {}
}

export class Keypoint {
  constructor(
    public position: Position,
    public _id: string,
    public score: number,
    public part: string
    ) {}
}

export class Position {
  constructor(
    public x: number,
    public y: number
    ) {}
}
